# Generated by Django 3.0 on 2021-03-24 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('addressOne', models.CharField(max_length=100)),
                ('addressTwo', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('industry', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=100)),
                ('inventory', models.FileField(upload_to='user_directory_auth/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='dave', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='dave', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mango',
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
