# Generated by Django 3.0 on 2021-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210324_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='addressOne',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='addressTwo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='inventory',
            field=models.FileField(blank=True, upload_to='user_directory_auth/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='zipCode',
            field=models.IntegerField(blank=True),
        ),
    ]
