# Generated by Django 3.0 on 2021-03-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210324_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='addressOne',
        ),
        migrations.RemoveField(
            model_name='business',
            name='addressTwo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='city',
        ),
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='business',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='business',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='business',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='state',
        ),
        migrations.RemoveField(
            model_name='business',
            name='website',
        ),
        migrations.RemoveField(
            model_name='business',
            name='zipCode',
        ),
    ]
