# Generated by Django 3.0 on 2021-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210325_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
